---
title: Jason Meridth
timezone: America/Chicago
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Blog of Jason Meridth - Learn, Converse, Share
disqus_shortname:
reading_time: true
words_per_minute: 200
logo: images/logo.jpg
excerpt_separator: "<!--more-->"
url: https://blog.jasonmeridth.com
menu:
- title: Home
  url: "/"
- title: Tags
  url: "/tags"
- title: About
  url: "/about"
- title: RSS
  url: "/feed.xml"
owner:
  name: Jason Meridth
  site: https://blog.jasonmeridth.com
  avatar: images/avatar.jpg
  bio: My name is Jason Meridth. I am a continuously learning senior software developer/devops/team
    lead/development manager trying to not let best be the enemy of better. I reserve
    the right to change my mind upon obtaining more information.  I am also the owner and
    principal software consultant at Meridth, LLC.  If you have any software, hardward, networking,
    process, etc needs please don't hesitate to reach out to me.
  email: jason@meridth.io
  phone: 210-383-9375
  twitter: jmeridth
  github: jmeridth
twitter:
  username: jmeridth
  image: /images/meridth_llc_cog.png
social:
- title: github
  url: https://github.com/jmeridth
- title: linkedin
  url: https://br.linkedin.com/in/jmeridth
- title: twitter
  url: https://twitter.com/jmeridth
background:
google_analytics: UA-38456568-3
google_verify: 2LRsgnHFM86Lph9HmYJGK6Uoa-Fn75nSU9YdAGbZAo4
locale: en_US
future: true
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: "/posts/:title/"
paginate: 5
float_share: true
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true
include:
- ".htaccess"
exclude:
- demo/*
- lib
- config.rb
- Capfile
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-gist
