# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:           posts/:title/

# Setup
title:               Jason Meridth's Blog
tagline:             'Learn, Converse, Share'
description:         'Learn, Converse, Share'
url:                 http://localhost:4000
baseurl:             ''
paginate:            5
comments:            true
disqus_shortname:    jasonmeridth

# About/contact
author:
  name:              Jason Meridth
  url:               http://jasonmeridth.com
  email:             jmeridth@gmail.com

# Custom vars
version:             1.0.0
about:               http://jasonmeridth.com
github:              https://github.com/jmeridth
twitter:             https://twitter.com/jmeridth
linkedin:            https://linkedin.com/in/jmeridth

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-feed
  - jekyll-paginate
