# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: posts/:title/

# Setup
title: Jason Meridth's Blog
tagline: 'Learn, Converse, Share'
description: 'Learn, Converse, Share'
url: http://blog.jasonmeridth.com
baseurl: ''
paginate: 5
comments: true
disqus_shortname: jasonmeridth

# About/contact
author:
  name: Jason Meridth
  url: http://jasonmeridth.com
  email: jmeridth@gmail.com
  twitter: jmeridth
  picture: /assets/images/jason.png

# Custom vars
version: 1.0.0
about: http://jasonmeridth.com
feed:
  url: /feed.xml
github:
  url: https://github.com/jmeridth
twitter:
  url: https://twitter.com/jmeridth
  username: jmeridth
linkedin:
  url: https://linkedin.com/in/jmeridth
bitbucket:
  url: https://bitbucket.org/jmeridth
googleplus:
  url: https://plus.google.com/+JasonMeridth

timezone: America/Chicago
logo: /assets/images/logo.png

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
